### ISSUE TITLE
Have all issues in one place

### ISSUE THREAD

**Issue by itsP33t** [simrail/EDR#28]
We should move all existing issues from the old issues repo here, write it to the readme that it moved, update it on the website and disable the issues feature there. I can do it if you want.
It's probably a nightmare for people who doesn't have access to the project to hop between those two repos 😄

**Comment by DKFN** [comment]
True ! Already a nightmare for us :smile:

**Comment by itsP33t** [comment]
Then i will start working on migrating the issues here

**Comment by itsP33t** [comment]
I've successfully migrated all issues from the old repo to this one. There is one issue that is prompting users to create a issue here instead :)
