### ISSUE TITLE
Early / late minute counter

### ISSUE THREAD

**Issue by itsP33t** [simrail/EDR#34]
These green and red counters currently show:

- Time remaining until scheduled arrival (in green)
- Elapsed time since scheduled arrival?

This is somewhat counterintuitive. These colorized counters usually show estimated delay/earliness based on live data. This could be improved based on the new pathfinding feature and path weighting. See also https://github.com/DKFN/edr-issues/issues/62

**Comment by Tallyrald** [comment]
Closing in favor of https://github.com/simrail/EDR/issues/44
