### ISSUE TITLE
New trains have incorrect max speed. 243 / 423 trains does no have the correct max speed

### ISSUE THREAD

**Issue by DKFN** [simrail/EDR#52]
Probably will need a more clever way to fetch the max speed that includes the beginning of the train number
![image](https://user-images.githubusercontent.com/19529767/219905081-444727a9-bfbb-492f-be43-9ba89716f620.png)

**Comment by Tallyrald** [comment]
If max speeds ever make it back onto the EDR, it will be a brand new way of doing it, so I'll close this for now.

**Comment by matejdro** [comment]
https://forum.simrail.eu/topic/4534-en-timetables-and-speed-limits/ maybe this could help? Someone made a table of all trains with their speeds.

**Comment by DKFN** [comment]
That is a nice idea, there is also anorther possible way the EDR endpoint now has a "maxSpeed" per station object

```json
      {
        "nameOfPoint": "Warszawa Wschodnia",
        "nameForPerson": "Warszawa Wschodnia",
        "pointId": "4824",
        "supervisedBy": "Warszawa Wschodnia",
        "radioChanels": " ",
        "displayedTrainNumber": "14141",
        "arrivalTime": "2024-01-05 20:31:00",
        "departureTime": "2024-01-05 20:34:00",
        "stopType": "CommercialStop",
        "line": 2,
        "platform": "I",
        "track": 12,
        "trainType": "ECE",
        "mileage": 4.254,
        "maxSpeed": 60,
        "stationCategory": "B"
      }
      ```
      
I am not sure however if this data is capped at the train maximum possible speed or not. But if it is we can maybe use the max of the array and return the value.
