### ISSUE TITLE
Mobile view enhancements

### ISSUE THREAD

**Issue by Tallyrald** [simrail/EDR#91]
The mobile view is janky and hard to read. Information presented could probably be cut down a little bit.

**Comment by DKFN** [comment]
Despite the UI being too packed, a bug also occurs and It seems the main culprit of this render is the overflow: auto removed on the overflowing headers divs.

No overflow auto:
![image](https://github.com/simrail/EDR/assets/19529767/dcbfd3ba-f15f-4378-90f6-1b855d151022)

Overflow auto
![image](https://github.com/simrail/EDR/assets/19529767/54f0f29c-5f7b-4af9-872e-264854ce6f0b)

**Comment by Tallyrald** [comment]
Today's release contains some small changes to this view, hopefully it helps.
