### ISSUE TITLE
Traxx/E186 passenger trains not shown in train selection screen

### ISSUE THREAD

**Issue by FrozenTux** [simrail/EDR#97]
Hello,

Passenger trains pulled by Traxx locomotives are not shown in the selection screen of the driver mode. These locos operate on the 13xxx and 14xxx lines alternating with the EP08, on top of their freight services (which are displayed).

This is just a display bug as entering the train number manually in the URL works.

This is caused by the filter conditions used to separate the trains by category here (https://github.com/simrail/EDR/blob/a41af9361b96adb2ca600facab501429d3c77f23/frontend/src/SelectMenu/TrainSelect.tsx#L90) not including the traxx name.

**Comment by Tallyrald** [comment]
Thanks! I'll return to the project sometime after the next update for the game. I'll take a look at this issue and PR (thanks!) at that time. :)
