### ISSUE TITLE
Wrong timezone on EDR dispatch 

### ISSUE THREAD

**Issue by krupniok200** [simrail/EDR#99]
After change timezone in Europe EDR still show trains on summer time, not winter. Website shows winter time, good for sever time.

![image](https://github.com/simrail/EDR/assets/48364777/726ea38d-5a0c-4745-a181-29784e69e4cc)

**Comment by Tallyrald** [comment]
This seems to be a game API issue, the EDR timetable times served through their API are offset by an hour.

**Comment by krupniok200** [comment]
On ingame EDR time is correct, i tried on PL4 server on Łazy Łc dispatch.

**Comment by Tallyrald** [comment]
Unfortunately the ingame EDR uses different data than the public API so it cannot be compared to what we see on our tool.

**Comment by Tallyrald** [comment]
Timezones were fixed by the game update yesterday, closing this issue.
